### librer√≠as

In [ ]:
import pandas as pd

### carga de datasets

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
hv_path = '/content/drive/MyDrive/Proyecto Introduccion a la Ciencia de Datos'

In [ ]:
ventas = pd.read_csv(f'{hv_path}/output/propiedades_en_venta.csv')

In [ ]:
alquiler = pd.read_csv(f'{hv_path}/output/propiedades_en_alquiler.csv')

In [ ]:
precioxmt2 = pd.read_csv(f'{hv_path}/output/precioxmt2.csv')

In [ ]:
precioxmt2.head()

         sector         pmc
0  Abel Gilbert  341.420856
1       Acacias  507.023203
2      Alborada  819.085921
3       Argelia  435.426671
4     Atarazana  857.244304

In [ ]:
data_sectores = pd.read_csv(f'{hv_path}/data/sectores_datos.csv')
data_sectores.drop(columns = ['Unnamed: 0'], inplace = True)

In [ ]:
data_sectores.head()

,Nombre_sector,N centros Comerciales,Sector,Ciudad,AreaMT2
0,Urbanizacion La Saiba,0.0,Sur,Guayaquil,649435.136551
1,Ciudadela 9 de Octubre,1.0,Sur,Guayaquil,397449.483519
2,Galavsa,0.0,Norte,Guayaquil,815731.334534
3,Parroquia Pedro Carbo,3.0,Norte,Guayaquil,649391.211979
4,Parroquia Olmedo,3.0,Sur,Guayaquil,427976.177849

In [63]:
ipc = pd.read_csv(f'{hv_path}/output/ipc_anual2017.csv')

In [64]:
ipc.head()

     neighborhood  ingpc_mean      gini  ingpc_median         iqr
0    Abel Gilbert  186.582404  0.249501       165.375  117.555283
1         Acacias  297.917603  0.297507       220.250  289.375000
2  Academia Logos  786.931579  0.293687       755.000  543.075000
3        Alborada  422.237240  0.300916       380.000  352.372917
4         Arcadia  786.931579  0.293687       755.000  543.075000

In [ ]:
alquiler.shape

(35127, 17)

In [ ]:
ventas.shape

(35116, 18)

In [ ]:
ventas['bathrooms'].isna().sum()

5223

In [ ]:
alquiler['bathrooms'].isna().sum()

1803

In [ ]:
alquiler.dropna(subset=['bathrooms'], inplace=True)
ventas.dropna(subset=['bathrooms'], inplace=True)

### m√©tricas

In [ ]:
data_sectores['CCMC'] = data_sectores['N centros Comerciales']/data_sectores['AreaMT2']

In [ ]:
df = data_sectores[['Nombre_sector', 'CCMC']]

In [ ]:
alq_prom = alquiler.groupby('Nombre_sector', as_index=False)['price'].mean()
alq_prom.columns = ['Nombre_sector', 'AP']

In [ ]:
df = df.merge(alq_prom, how='left')

In [ ]:
df

              Nombre_sector          CCMC           AP
0     Urbanizacion La Saiba  0.000000e+00   476.372549
1    Ciudadela 9 de Octubre  2.516043e-06   294.545455
2                   Galavsa  0.000000e+00  8100.000000
3     Parroquia Pedro Carbo  4.619711e-06   810.096070
4          Parroquia Olmedo  7.009736e-06  1184.627451
..                      ...           ...          ...
234          La Ecuatoriana  1.617982e-07   520.000000
235                 Guamani  1.257026e-07  1326.323529
236              Mapasingue  2.765365e-06   989.440141
237              Bellavista  1.557540e-06   386.923077
238                I√±aquito  3.135226e-06   579.398408

[239 rows x 3 columns]

In [ ]:
df.isna().sum()

Nombre_sector     0
CCMC              0
AP               33
dtype: int64

In [ ]:
df['AP'].fillna(0, inplace=True)

In [ ]:
df.isna().sum()

Nombre_sector    0
CCMC             0
AP               0
dtype: int64

In [ ]:
vent = ventas.drop(columns=['precioxmt2'])

In [ ]:
properties = pd.concat([vent, alquiler])

In [ ]:
results = properties.groupby('Nombre_sector')['id'].count().sort_values(ascending=False).reset_index()

In [ ]:
results

      Nombre_sector     id
0          I√±aquito  10908
1            Urdesa   3010
2        La Kennedy   2945
3            La Paz   2529
4    Mariscal Sucre   2379
..              ...    ...
224      Geranios 1      1
225       Rio Lindo      1
226     Monte Sinai      1
227       Los Lagos      1
228      El Cortijo      1

[229 rows x 2 columns]

In [ ]:
idx = results['id'] > 500
results[idx]

           Nombre_sector     id
0               I√±aquito  10908
1                 Urdesa   3010
2             La Kennedy   2945
3                 La Paz   2529
4         Mariscal Sucre   2379
5                 Ceibos   2273
6               Ponceano   1932
7                El Inca   1757
8               Alborada   1644
9                Garzota   1340
10              Carcelen   1203
11     Belisario Quevedo   1142
12                Sauces   1131
13   San Isidro del Inca   1050
14      Puerto Santa Ana    985
15  Parroquia Rocafuerte    930
16            Villa Club    856
17               La Joya    772
18     Ciudadela Vernaza    733
19            Mucho Lote    685
20               Kennedy    619
21             Atarazana    613
22               Samanes    589
23               Urdenor    586
24            San Felipe    549
25       Ciudadela Adace    521
26           Puerto Azul    505

In [ ]:
bath_mean = properties.groupby('Nombre_sector')['bathrooms'].mean().reset_index()

In [ ]:
df = df.merge(bath_mean)

In [ ]:
idx = properties['property_type'].isin(['Oficina', 'Local comercial'])
actividad_comercial = properties[idx].groupby('Nombre_sector')['id'].count().reset_index()

In [ ]:
df = df.merge(actividad_comercial, how='left')

In [ ]:
df

              Nombre_sector          CCMC           AP  bathrooms      id
0     Urbanizacion La Saiba  0.000000e+00   476.372549   3.403614     2.0
1    Ciudadela 9 de Octubre  2.516043e-06   294.545455   2.222222     NaN
2                   Galavsa  0.000000e+00  8100.000000   4.000000     NaN
3     Parroquia Pedro Carbo  4.619711e-06   810.096070   2.011682    50.0
4          Parroquia Olmedo  7.009736e-06  1184.627451   2.018018     2.0
..                      ...           ...          ...        ...     ...
224          La Ecuatoriana  1.617982e-07   520.000000   2.626866     1.0
225                 Guamani  1.257026e-07  1326.323529   2.263514     NaN
226              Mapasingue  2.765365e-06   989.440141   1.960976    26.0
227              Bellavista  1.557540e-06   386.923077   2.510288     NaN
228                I√±aquito  3.135226e-06   579.398408   1.875504  1099.0

[229 rows x 5 columns]

In [ ]:
df['id'].fillna(0, inplace=True)

In [ ]:
df.columns = ['sector', 'ccmc', 'ap', 'bps', 'ac']

In [ ]:
df = precioxmt2.merge(df)

In [66]:
ipc[['ingpc_mean', 'neighborhood']]

     ingpc_mean    neighborhood
0    186.582404    Abel Gilbert
1    297.917603         Acacias
2    786.931579  Academia Logos
3    422.237240        Alborada
4    786.931579         Arcadia
..          ...             ...
92   270.232101       Turubamba
93   358.164657         Urbanor
94   434.587815         Urdenor
95   190.114522        Vergeles
96  1074.472222       Vista Sol

[97 rows x 2 columns]

In [70]:
df = df.merge(ipc[['neighborhood', 'ingpc_mean']], how='left', left_on='sector', right_on='neighborhood')
df = df.drop(columns='neighborhood')

In [73]:
df

,sector,pmc,ccmc,ap,bps,ac,ingpc_mean
0,Abel Gilbert,341.420856,0.000000e+00,3000.000000,1.866667,0.0,186.582404
1,Acacias,507.023203,0.000000e+00,245.000000,2.200000,1.0,297.917603
2,Alborada,819.085921,4.157044e-06,389.192825,2.066910,113.0,422.237240
3,Argelia,435.426671,4.232569e-07,1660.279070,2.155340,9.0,191.006255
4,Atarazana,857.244304,1.251978e-06,617.601790,2.236542,19.0,553.194133
...,...,...,...,...,...,...,...
56,Sauces,686.392528,9.823048e-07,295.268797,2.230769,10.0,364.891111
57,Solanda,517.208887,2.739629e-06,451.052632,2.456140,3.0,234.612433
58,Turubamba,542.188739,1.692989e-06,540.645161,2.450331,4.0,270.232101
59,Urdenor,936.585279,7.700748e-06,401.451220,2.317406,12.0,434.587815
60,Vergeles,735.707143,3.591105e-06,639.761905,2.418269,6.0,190.114522

In [74]:
df.to_csv(f'{hv_path}/output/dataset.csv', index=False)